### PR TITLE
Some cleanup and python support [dont merge yet]

### PR DESCRIPTION
**Pull request by mdzik**
this is for review
- Save/Load have *very* different behaviour depending on on of parameters: splitted into to XML tags and handlers
- New Python handler placeholder added, new compilation flags and some configere.ac modifications, Jenkins needed for all models :)
Probably few commit before merge ready

### CODE REVIEW

**Comment by mdzik** [comment]
merge candidate, if compiled

**Comment by llaniewski** [comment]
python is failing to install.

also: please move the python installation to tools/install.sh, like all the rest

**Comment by mdzik** [comment]
done


2015-08-28 13:53 GMT+02:00 Łukasz Łaniewski-Wołłk <notifications@github.com>
:

**Comment by llaniewski** [comment]
Move the BoundaryHelper experiments to a new separate d2q9 model (lets call it "d2q9_farfield" for instance)

**Comment by mdzik** [comment]
done, sorki :)

**Comment by mdzik** [comment]
...and i works with MPI :D

**Comment by llaniewski** [comment]
Looks ok. Merging.

**Pull request merged**
